(ns leiningen.tasks
  (:require [leiningen.lein-sass.renderer :refer :all]
            [leiningen.lein-sass.options :refer :all]
            [cemerick.pomegranate :only [add-dependencies]]))

(defn- once [options]
  "Compiles files once"
  (render-all! options false true))

(defn- auto
  "Automatically recompiles when files are modified"
  [options]
  (render-all! options true))

(defn- clean
  "Removes the autogenerated files"
  [options]
  (clean-all! options))

(defn sass
  {:help-arglists [once auto clean]
   :subtasks [once auto clean]}

  ([project]
    (exit-failure (lhelp/help-for sass)))

  ([project subtask & args]
    (if-let [options (extract-options project)]
      (case subtask
        "once"  (once options)
        "auto"  (auto options)
        "clean" (clean options)
        (task-not-found subtask))
      (exit-failure))))
