(ns leiningen.tasks
  (:require [leiningen.lein-sass.renderer :refer :all]
            [cemerick.pomegranate :only [add-dependencies]]))

(def ^:private default-options {:src "resources"
                                :output-extension ""
                                :delete-output-dir true
                                :auto-compile-delay 250
                                :style :nested
                               })

(defn- normalize-hooks [options]
  (let [hooks            (into #{} (:ignore-hooks options))
        normalized-hooks (if (:compile hooks)
                           (disj (conj hooks :once) :compile)
                           hooks)]
    (assoc options :ignore-hooks normalized-hooks)))

(defn extract-options [project]
  (if :sass project
    (merge default-options (normalize-hooks options))
    (println "No sass entry found in project definition.")))

(defn- once [options]
  "Compiles files once"
  (render-all! options false true))

(defn- auto
  "Automatically recompiles when files are modified"
  [options]
  (render-all! options true))

(defn- clean
  "Removes the autogenerated files"
  [options]
  (clean-all! options))

(defn sass
  {:help-arglists [once auto clean]
   :subtasks [once auto clean]}

  ([project]
    (exit-failure (lhelp/help-for sass)))

  ([project subtask & args]
    (if-let [options (extract-options project)]
      (case subtask
        "once"  (once options)
        "auto"  (auto options)
        "clean" (clean options)
        (task-not-found subtask))
      (exit-failure))))
