(ns leiningen.tasks
  (:require [leiningen.lein-sass.renderer :refer :all]
            [leiningen.lein-sass.options :refer :all]
            [leiningen.help :as lhelp]
            [leiningen.core.main :as lmain]
            [cemerick.pomegranate :only [add-dependencies]]))

(defn- once [options]
  "Compiles files once"
  (render-all! options false true))

(defn- auto
  "Automatically recompiles when files are modified"
  [options]
  (render-all! options true))

(defn- clean
  "Removes the autogenerated files"
  [options]
  (clean-all! options))

(defn sass
  {:help-arglists [once auto clean]
   :subtasks [once auto clean]}

  ([project]
    ((resolve 'leiningen.core.main/abort) (lhelp/help-for "sass")))

  ([project subtask & args]
    (if-let [options (extract-options project)]
      (case subtask
        "once"  (once options)
        "auto"  (auto options)
        "clean" (clean options)
        (lmain/warn subtask " not found."))
      ((resolve 'leiningen.core.main/abort) "Invalid options in project.clj."))))
